[package]
name = "hcb-transaction-tracker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = "0.12.5"
serde = "1.0.204"
serde_json = "1.0.120"
worker = "0.3.0"
